# single_lora_conll03.yaml
task_name: conll03
task_type: ner
num_labels: 9
class_names: ['O', 'B-PER', 'I-PER', 'B-ORG', 'I-ORG', 'B-LOC', 'I-LOC', 'B-MISC', 'I-MISC']

backbone_model: dslim/bert-base-NER

lora:
  r: 8
  alpha: 16
  dropout: 0.1
  target_modules: ["query", "value"]

train:
  seed: 42
  batch_size: 16
  learning_rate: 2e-4
  num_epochs: 4
  # num_epochs: 1
  max_seq_length: 128
  optimizer: adamw
  lr_scheduler: linear
  warmup_ratio: 0.1

early_stopping:
  enabled: true
  patience: 2
  monitor: val_f1   # best model
  mode: max          # val_loss是min，val_acc是max, val_f1是max

data:
  train_file: ${DATA_ROOT}/single_lora_data/conll2003_train_07052025_1605.json
  val_file: ${DATA_ROOT}/single_lora_data/conll2003_validation_07052025_1605.json
  label2id_file: ${DATA_ROOT}/label2id_for_conll03.json 

output:
  save_dir: ${DRIVE_ROOT}/DynamoRouterCheckpoints/adapter_conll03
  save_best_only: true
  monitor_metric: val_f1  # 自动对齐 early_stopping
  save_lora_adapter: true
  save_task_head: true
  log_dir: ${DRIVE_ROOT}/DynamoRouterLogs/adapter_conll03

# ========= 调试专用 =========
# 调试时EPOCH可改为: num_epochs: 1
# 去COLAB训练时要把 skip_training: false, limit_batches: None 
debug:
  skip_evaluation: false    # 不跳评估，让模型至少走一次评估流程
  skip_training: false 
  limit_batches: null
  # skip_training: true       # 本地测试时用：跳过训练主循环，只测试evaluate和保存流程
  # limit_batches: 2          # 本地测试时用：：只取前2个batch进行evaluate（None表示不限制）